# Generated by Django 5.0.1 on 2024-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_COURSE', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Course',
            field=models.CharField(choices=[('Web Designing', 'Web Designing'), ('Full Stack Python', 'Full Stack Python'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development')], default=' ', max_length=100),
        ),
    ]
