# Generated by Django 5.0.1 on 2024-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_COURSE', '0003_contactus_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Course',
            field=models.CharField(choices=[('Full Stack Java', 'Full Stack Java'), ('Full Stack Python', 'Full Stack Python'), ('Data Science', 'Data Science'), ('AWS', 'AWS'), ('MERN Stack', 'MERN Stack'), ('Spoken English', 'Spoken English'), ('Data Analytics', 'Data Analytics'), ('DevOps', 'DevOps')], default=' ', max_length=100),
        ),
    ]
